# **Multiple Linear Regression**

# ***1. Import Libraries***

In [ ]:
import pandas as pd #data manipulation
import numpy as np #mathematical operation
import matplotlib.pyplot as plt #data visulalization
from sklearn.model_selection import train_test_split #test/train data
from sklearn.linear_model import LinearRegression #data modeling/data training
from sklearn.metrics import mean_squared_error

# ***2. Creating a Synthetic Dataset***

In [ ]:
np.random.seed()
x = np.random.rand(100,3)
y = x [:,0] * 150000 + x[:,1]  *100000 + x[:,2] * 50000 + 50000

# ***3. Converting to a DataFrame***

In [ ]:
data = pd.DataFrame(x, columns=['Size', 'Bedroom', 'Age'])
data['Price'] = y



x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2,random_state=42)
data.head()

Size   Bedroom       Age          Price
0  0.380950  0.019259  0.965079  157322.316271
1  0.653745  0.311861  0.945914  226543.599312
2  0.985067  0.530631  0.192108  260428.517758
3  0.918962  0.207083  0.604509  238777.998083
4  0.305205  0.882189  0.958162  231907.720898

# ***4. Initializing the Model***

In [ ]:
model = LinearRegression()

# ***5. Fitting the Model***

In [ ]:
model.fit(x_train, y_train)

LinearRegression()

# ***6. Making Predictions***

In [ ]:
y_predict = model.predict(x_test)
print(x_test)
print(y_predict)

[[0.69422637 0.90870042 0.55405293]
 [0.09510173 0.97996781 0.53350731]
 [0.06540445 0.09599874 0.90966714]
 [0.23386265 0.92050443 0.62841967]
 [0.93023712 0.88547645 0.39633186]
 [0.69394237 0.58934622 0.06274837]
 [0.39347484 0.35507355 0.66490539]
 [0.78889173 0.02004183 0.98845744]
 [0.65542821 0.45618089 0.03076304]
 [0.38094963 0.01925941 0.96507862]
 [0.89981897 0.68268514 0.18680703]
 [0.23770856 0.30729948 0.47295408]
 [0.30039224 0.88121291 0.95750146]
 [0.41433693 0.04105729 0.11934808]
 [0.4579062  0.18386423 0.70524115]
 [0.30520457 0.88218916 0.9581624 ]
 [0.99091509 0.65920344 0.56634756]
 [0.27996238 0.49031069 0.52895929]
 [0.57648727 0.4080774  0.92604507]
 [0.32760233 0.97526228 0.27008082]]
[272706.64412549 188937.40573201 114893.89893125 208550.82381456
 297899.80683553 216163.39645992 177773.85       219760.81527428
 195470.47234027 157322.31627142 262581.71124633 140033.93570834
 231055.19991161 122223.67190251 172334.4105981  231907.72089761
 292874.98662142 16

# ***7. Calculating the Mean Squared Error***

In [ ]:
mse = mean_squared_error(y_test, y_predict)
print("Mean Squared Error: ", (mse))

Mean Squared Error:  1.334076891925523e-21


# ***8. Predicting the Price of a New House Price***

In [ ]:
new_house = [[0.5,2,10]]
predicted_price = model.predict(new_house)
print("Predicted: ", (predicted_price[0]))

Predicted:  825000.0
